In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(pd.read_excel(r"F:\LPU\Code\Python\templates\final_data.xlsx"))
pd.set_option('display.max_columns', None)
df.sample(1)

,lead_number,first_name,Lead Id,inbound_phone_call_counter,outbound_phone_call_counter,lead_stage,lead_score,owner,activity,date_of_call,status_x,call_duration_sec,calls_done_by,contacted_x,call_time,sales_squad,squad_role,lead_id,created_time,Ad Name,Campaign Name,form_name,platform,graduation_degree,graduation_percentage,work_experience,mapped,contacted_y,lsq_lead_stage,lsq_lead_owner,lsq_source,derived_score,Name,Lead ID,created_date,paid_date,cohort,source,agent,counsellor,prospect_id,status_y,Candidate Name,Counselor Name,Block Amount Received Date,Univ. Pitched,Candidate Preferred College #1,Candidate Preferred College #2,10th Percentage,12th Percentage,UG - CGPA (out of 10),GPA (Out of 4),PG - CGPA or %,Work Exp.,Highest Education,Designation - Company Name,Candidate Application Status,Candidate Loan Status,Remarks - General,Reason for dropping,"If dropped, mention stage of the application",,KYC & Acad Documents Received,Tech Exam Scores,Coding Test Score,English Exam Scores,Exam Taking Date,English Interview Score (15),Tech. interview Score (10),.1,Application Type,Intake Status,.2,Choice of School #1,Choice of Program #1,Passport #1,Resume #1,Degree #1,Transcript #1,Application Fee #1,LOR #1,SOP #1,Pending Stage #1,Application Status #1,Application Initation Date #1,App Partially Submitted Date #1,Application Submission Date #1,Offer Letter #1,Offer Letter Provision Date #1,Deposit #1,Deposit Date Paid #1,.3,Choice of School #2,Choice of Program #2,Application Fee #2,LOR #2,SOP #2,Pending Stage #2,Application Status #2,Application Initation Date #2,App Partially Submitted Date #2,Application Submission Date #2,Offer Letter #2,Offer Letter Provision Date #2,Deposit #2,Deposit Date Paid #2,.4,Choice of School #3,Choice of Program #3,Application Fee #3,LOR #3,SOP #3,Pending Stage #3,Application Status #3,Application Initation Date #3,App Partially Submitted Date #3,Application Submission Date #3,Offer Letter #3,Offer Letter Provision Date #3,Deposit #3,Deposit Date Paid #3,Remarks #3 (If Rejected),.5,Choice of School #4,Choice of Program #4,Application Fee #4,LOR #4,SOP #4,Pending Stage #4,Application Status #4,Application Initation Date #4,App Partially Submitted Date #4,Application Submission Date #4,Offer Letter #4,Offer Letter Provision Date #4,Deposit #4,Deposit Date Paid #4,Remarks #4 (If Rejected),.6,Choice of School #5,Choice of Program #5,Application Fee #5,LOR #5,SOP #5,Pending Stage #5,Application Status #5,Application Initation Date #5,App Partially Submitted Date #5,Application Submission Date #5,Offer Letter #5,Offer Letter Provision Date #5,Deposit #5,Deposit Date Paid #5,Remarks #5 (If Rejected),.7,IIM / IIT Status,Loan Status,Loan Partner I,Loan Partner II,Loan Application Submit Date,Existing Loan,CIBIL SCORE,No. of defaults,.8,Aadhar Card,PAN Card,Passport,CV/Resume,CIBIL Score,Bank Statement (Savings - 6mo),Affidavit Letter,Sponsorship Letter,Offer Letter,Offer Letter Submission Date,.9,Financials Submission,Financials Submission Date,i20 Provisioned,i20 Provisioned Date,Remarks,Status,SOP Status,.10,is_dropped,days_to_pay,Pitched Preferred Univ
2628,2297433,akhil,l:366535416257116,0,10,Warm,0,Afzal Ahmad,Outbound Phone Call Activity,2024-03-22 12:14:00,NotAnswered,30,AfzalAhmad,NaN,2024-03-22 12:14:00,NaN,NaN,l:366535416257116,2024-03-08 15:32:00,#6 ( Graphic ) - Master's Degree In 12 Months,USP Study Abroad_Generic_240224,BM - US pathway Webinar Form - Higher Intent -...,Facebook,Others,75,5,Mapped,Contacted,Document Collection,Swapnil Awasthi,Zoom Webinar,2.5,Akhil,l:366535416257116,2024-03-08,2024-04-03,Cohort 2,Zoom Webinar,Afzal Ahmad,Shashwat,1a9bf8c9-909d-4488-abeb-dc9c3c4b1869,ACTIVE TOKEN,Akhil,Shashwat Shourya,2024-04-03 00:00:00,NaN,"RIT, Saunders College of Business","Rider University, Brodsky College of Business",84.33,80.3375,7.8,3.12,NaN,4.0,B.com,DevOps Engineer - Orion Innovation,Deposit Paid & IIM/IIT Paid,Loan Application Pending,RIT (MSBA) & Rider (MS-IS) submitted on 12/04 ...,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall 2024,NaN,"RIT, Saunders College of Business",MS in Business Analytics,0,0,0,0,1,1,1,Completed,Withdrawn,45387.0,NaN,45394,Awaited,NaN,0.0,NaN,NaN,DePaul Kellstadt Graduate School of Business,MS in Business Analytics,1,1,1,Completed,Submitted,45387.0,45394.0,45398.0,Received,45400.0,1.0,45408.0,NaN,"Rider University, Brodsky College of Business",MS in Information Systems,1.0,1.0,1.0,Completed,Submitted,45391.0,NaN,45394.0,Rejected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,"Application Fee #1, LOR #1, SOP #1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,"Application Fee #1, LOR #1, SOP #1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Paid,Loan Sanctioned- Self,NaN,NaN,NaN,NaN,,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,Fall,NaN,NaN,0,26,False

In [4]:
df.loc[:, 'total calls'] = df['inbound_phone_call_counter'] + df['outbound_phone_call_counter']

In [5]:
df['Lead Id'].duplicated().any()

np.True_

In [6]:
# df.loc[:, 'avg call duration'] = df['call_duration_sec']

In [9]:
cols_for_pred = ['Campaign Name', 'platform', 'graduation_degree', 'days_to_pay', 'Pitched Preferred Univ', 'derived_score', 'Highest Education']
feature_col = ['is_dropped']

In [15]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
X = df[cols_for_pred]
y = df[feature_col]
y=y.values.ravel()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = X.select_dtypes(include=['object']).columns

numeric_transformer = Pipeline(steps=[('scaler', StandardScaler())])
categorical_transformer = Pipeline(steps=[('onehot', OneHotEncoder(handle_unknown='ignore'))])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ])

model = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', LogisticRegression())])

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9615912208504801

In [16]:
from sklearn.metrics import r2_score, mean_squared_error

y_true = y_test
y_pred = model.predict(X_test)

r2 = r2_score(y_true, y_pred)
mse = mean_squared_error(y_true, y_pred)

print("R-squared:", r2)
print("Mean Squared Error:", mse)

R-squared: 0.7886300093196645
Mean Squared Error: 0.038408779149519894

In [23]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
X = df[cols_for_pred]
y = df[feature_col]
y=y.values.ravel()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = X.select_dtypes(include=['object']).columns

numeric_transformer = Pipeline(steps=[('scaler', StandardScaler())])
categorical_transformer = Pipeline(steps=[('onehot', OneHotEncoder(handle_unknown='ignore'))])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ])

model = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', RandomForestClassifier())])

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [17]:
ndf = pd.DataFrame(pd.read_excel(r"F:\LPU\Code\Python\templates\new_df.xlsx"))
pd.set_option('display.max_columns', None)
ndf.sample(1)

,lead_number,first_name,Lead Id,inbound_phone_call_counter,outbound_phone_call_counter,lead_stage,lead_score,owner,activity,date_of_call,status,call_duration_sec,calls_done_by,contacted_x,call_time,sales_squad,squad_role,lead_id,created_time,Ad Name,Campaign Name,form_name,platform,graduation_degree,graduation_percentage,work_experience,mapped,contacted_y,lsq_lead_stage,lsq_lead_owner,lsq_source,derived_score
45343,1122500,INDER MURLI LADWANI,l:2341591326229382,0,20,Not Interested,2,Janvi Aggarwal,Outbound Phone Call Activity,2024-05-04 11:55:00,Answered,41,JanviAggarwal,NaN,2024-05-04 11:55:00,NaN,NaN,l:2341591326229382,2024-02-04 19:26:00,#6 ( Graphic ) - Master's Degree In 12 Months,CBO - USP Masterclass Cold [ 15th Dec ] - High...,BM - US pathway Webinar Form - Higher Intent -...,Facebook,MCA,60.0,1.0,Mapped,Contacted,Not Interested,Janvi Aggarwal,B.Tech 19-20 Grad,-0.5

In [25]:
cpdf = pd.DataFrame(pd.read_excel(r"F:\LPU\Code\Python\templates\cleaned_campaign_performance.xlsx"))
pd.set_option('display.max_columns', None)
cpdf.sample(1)

,dates,campaign_name,campaign_start_date,creative_name,total_spent,impressions,clicks,click_through_rate,leads,platform,adset_name
1843,2023-12-20,CBO - USP Masterclass Cold [ 23rd Nov ] - More...,2023-11-23,#5 ( Graphic ) - Get Master's Degree in Just 1...,41.15,84,0,0.0,0.0,Facebook,Open Targeting - Advantage+ audience [ 31st Oct ]

In [34]:
len(cpdf['creative_name'].unique())

146

In [26]:
len(cpdf)

28534

In [27]:
cpdf['campaign_name'].duplicated().sum()

np.int64(28493)

In [29]:
len(cpdf['campaign_name'].unique())

41

In [32]:
x = cpdf.groupby('campaign_name')[['total_spent', 'impressions', 'clicks', 'click_through_rate', 'leads']].sum().reset_index()

In [33]:
x

,campaign_name,total_spent,impressions,clicks,click_through_rate,leads
0,CBO - USP Masterclass Cold [ 15th Dec ] - High...,186700.48,610938,12853,1268.645940,1346.00
1,CBO - USP Masterclass Cold [ 15th Dec ] - More...,136833.11,1302917,5505,1002.565790,654.00
2,CBO - USP Masterclass Cold [ 23rd Nov ] - High...,196255.37,862724,9469,2127.476382,1093.00
3,CBO - USP Masterclass Cold [ 23rd Nov ] - More...,254353.16,868290,11100,1679.385069,731.00
4,USP Masterclass Cold [ 14th Dec ] - Link Click Ad,10452.55,871201,18578,179.542379,0.00
5,USP Masterclass Cold [ 23rd Nov ] - More volum...,122867.55,527531,4542,635.480576,216.00
6,USP Masterclass Cold [ 31st Oct ] - Higher Int...,205642.99,713599,7516,2181.748817,888.00
7,USP Masterclass Cold [ 31st Oct ] - More Volum...,109113.64,536447,4884,1064.059596,568.00
8,USP Masterclass Cold [ 31st Oct ] - More volum...,92486.22,326810,2939,1092.149330,134.00
9,USP Study Abroad_Generic_240224,2126684.24,9265548,48531,7291.302704,4630.00
10,USP_2_Lead-gen-1_220124,484768.66,1668181,10480,3118.823794,2124.00
11,USP_2_Lead-gen-2_Top4-states_050424,194398.53,960204,3933,538.531918,395.00
12,USP_COOP-Drexel_More_Volume_No Logic_India_240124,126657.36,395467,5238,1144.072870,1096.00
13,USP_MS + Coop Campaign_240224,1501040.54,4506382,27762,2047.948722,4446.00
14,USP_Marketing+MBA_New Leads Campaign_240224,1125425.52,8106285,37727,570.031499,2390.00
15,USP_Program_Higher Intent_No Logic_India_220124,101866.32,596144,3027,534.665004,327.00
16,USP_Program_Higher Intent_No Logic_South-state...,178012.52,948123,3748,626.803675,309.00
17,USP_Program_Lead-gen_2_Generic_140223,80827.43,452962,2042,534.179804,235.00
18,USP_Program_Lead-gen_3_Co-op_140223,73726.11,330384,2102,333.612365,329.00
19,USP_Program_Lead-gen_4_MAR&MBA_140223,74697.63,261944,1455,115.150480,173.00
20,USP_Program_More-Volume_No Logic_India_220124,126886.43,746379,3617,862.473436,554.00
21,USP_Program_More-Volume_No Logic_South-states_...,126633.51,1153190,3332,342.751885,248.00
22,USP_Program_More-volume_With-Logic_India_220124,63193.02,197711,1771,1130.499313,336.00
23,USP_Program_More-volume_With-Logic_South-state...,109130.82,556972,2981,626.583974,171.00
24,USP_Search_APTNTSKA_250124,789571.12,178830,21663,13.451500,1360.00
25,USP_Search_India-ex-APTNTSKA_250124,199442.83,88614,3836,4.328100,430.00
26,USP_Video_ALL-India_Lead-Gen_Keywords_110324,25865.85,442455,10896,0.534000,52.00
27,USP_Video_APTLTSKA_Lead-Gen_160224,89981.07,1546844,29492,1.235100,155.98
28,USP_Video_APTLTSKA_Lead-Gen_Custom-intent_050324,155920.03,1220168,25558,3.223400,630.55
29,USP_Video_APTLTSKA_Lead-Gen_Keywords_050324,156281.16,1088979,16799,1.309400,350.64
30,USP_Video_APTLTSKA_Lead-Gen_Websites_050324,155646.87,1226818,26065,5.607800,569.17
31,USP_Video_India_EX-APTLTSKA_Lead-Gen_160224,76059.42,2302262,31294,0.928600,82.00
32,USP_Video_More_Volume_No Logic_India_New Link,198416.23,1246514,12420,1244.078309,1866.00
33,USP_Webinar2_270324,152751.12,806006,3418,95.595104,343.00
34,USP_Webinar_070324,752657.01,4125312,16957,370.372486,1616.00
35,US_Pathway_2_Lead_gen_1_091123,1884063.88,5751255,34923,11.279800,1232.00
36,US_Pathway_2_Lead_gen_2_091123,1469168.59,4225764,26627,7.089500,723.00
37,US_Pathway_2_Lead_gen_3_241123,1749087.89,6317435,36201,9.108900,874.00
38,US_Pathway_2_Lead_gen_4_220324,103022.64,348534,2082,1.448300,39.00
39,xCBO - USP Masterclass Cold [ 23rd Nov ] - Mor...,44937.43,195004,1594,138.351532,208.00
40,xCBO - USP Masterclass Cold [ 7th Dec ] - High...,13562.84,62852,644,158.954635,111.00

In [35]:
y = cpdf.groupby('creative_name')[['total_spent', 'impressions', 'clicks', 'click_through_rate', 'leads']].sum().reset_index()
y

,creative_name,total_spent,impressions,clicks,click_through_rate,leads
0,--,989013.95,267444,25499,17.779600,1790.0
1,#1 ( Graphic ) - Want To Build Your Career In ...,42737.40,179289,2963,1456.020399,98.0
2,#1 ( Graphic ) - Want To Build Your Career In ...,3600.73,233978,6706,40.263747,0.0
3,#10 ( Graphic ) - Get Into Top US Universitie,10243.63,24700,201,578.161143,33.0
4,#11 ( Graphic ) - Master's Degree In 12 Months...,32400.35,76641,502,347.343052,110.0
...,...,...,...,...,...,...
141,USP_kavita&steffi_VideoAd6,1310740.61,10704343,53875,363.218684,3013.0
142,USP_never-been-easier_C34,31816.32,94266,531,0.440300,5.0
143,USP_shreya&steffi_VideoAd8,60208.66,170640,1036,452.416175,85.0
144,USP_shreya_VideoAd7,46114.00,120820,1019,824.800212,98.0
145,less than a week_Static-3,1645.17,3479,34,53.759621,4.0